# Generated by Django 4.2.2 on 2023-08-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hire_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
    ]
