# Generated by Django 4.2.2 on 2023-08-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='company',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
