# Generated by Django 4.2.2 on 2023-08-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Skills',
        ),
    ]
